#!/bin/sh

#set -x
#set -ue

readonly alt_screen='\033[?1049h'
readonly normal_screen='\033[?1049l'
readonly hide_cur='\033[?25l'
readonly show_cur='\033[?25h'
readonly clear_screen='\033[2J'
readonly program=${0##*/}
readonly config_dir="${XDG_CONFIG_HOME:-"$HOME/.config"}"
readonly profiles="${config_dir%%/}/wfmux/profiles"

readonly logo_ls=$(cat <<EOF
                                ┌────────────
                                │
                                │                                            ┌───────
                                │                             ┌───┐          │
            ┌──┐                │                             │   │          │
            │  │                │                             │   │          │
            │  │           ┌────┼─────┬─────┬──────┬──┐       │   │    ┌─────┘
            │  │     ┌─    │    │     │     │      │  │       │   │    │
────────────┘  │     │     │    │     │     │      │  │       │   └────┼─────┐
               │     │     │    │     │     │      │  │       │        │     │
               │     │     │    │     │     └────  │  └───────┘        │     │
               ├─────┴─────┘    │     │            └──                 │     │
               │                │    ─┘                                │     │
               │                │            ──────────────────────────┘     │
               │                └─                                           │
         ──────┘                                                             │
                                                                             │
EOF
)
readonly logo_ms=$(cat <<EOF
                     ┌─────                           ┌───
                     │                                │
        ┌─┐          │                      ┌──┐      │
        │ │       ┌──┼───┬───┬───┬────┐     │  │  ┌───┘
        │ │   ┌─  │  │   │   │   │    │     │  │  │
────────┘ │   │   │  │   │   │   │    │     │  └──┼───┐
          │   │   │  │   │   │   │    │     │     │   │
          ├───┴───┘  │  ─┘   └─  │    └─────┘     │   │
          │          └─          └──              │   │
          │                              ─────────┘   │
       ───┘                                           │
EOF
)
readonly logo_ss='WFMUX'

readonly wfmux=$(cat<<EOF

     ┌──────────────┤ WFMUX
    ┌┴─────────────────────────────────────────────────┐
    │                                                  │
    ├───── Input a name for a new tmux session         │
    │                                                  │
    ├───── Input f⟨return⟩ to select a project         │
    │                                                  │
    ├───── Input ⟨return⟩ to drop to the terminal      │
    │                                                  │
    └──────────────────────────────────────────────────┘
EOF
)

wfmux_config="${config_dir%%/}/wfmux/wfmux.conf"
use_xdg=yes
runner=entr
runner_templates="$HOME/.config/wfmux/rtemplate"
dash_color=4
explorer=nnn
searcher=fzf
window_attributes_rest=20x20+10+20
window_attributes_file_selector=20x20+10+20
window_attributes_input_box=20x20+10+20
tbind_ops=nan
tbind_explorer=nan
tbind_select=nan

project_directory=$(cat <<-EOF
	$HOME/projects
	$HOME/aprojects
	$HOME/oprojects
	EOF
)

programs=$(cat <<-EOF
	pdf:      zathura
	text:     nvim
	video:    ffmpeg
	audio:    aplay
	image:    feh
	database: program_name
	EOF
)

usage() {
	cat <<EOF
Build an awesome dev workflow with tmux, fzf, nnn, and entr.
usage: wfmux [ [-c|-config|--config] *config_file* ] *operation_name*
       wfmux [ -h | -help | --help ]

Options:
     -h, -help, --help            print this help message.
     -c, -config, --config FILE   load *FILE* configuration file.

Operation names:
    open      fuzzyly select a project and open a new tmux session.
	runner    
    explore   open your favorite file manager on a popup tmux pane.
    select    fuzzyly select a file to open provided that they exist
              a recently used tmux session which carries the name of your
              project.
    commit    add to the index and commit changes to local repository.
    push      push to the preconfigured remote repositories.
	switch    fuzzyly switch between branches of your local repository.
EOF
	exit $1
}

die() {
	printf '%s\n' "$*"
	exit 1
}

main() {
	operation=
	gave_config=false

	[ $# -eq 0 ] && usage 1
	until [ $# -eq 0 ]; do
		case $1 in
			-h|-help|--help)
				usage 0
				;;
			-c|-config|--config)
				[ $# -eq 1 ] && wfmux_config=$2 || usage 1
				gave_config=true
				shift
				;;
			push|commit|select|explore|auto|open)
				operation=$1
				if [ -f "$wfmux_config" ]; then
					[ -r "$wfmux_config" ] || die "no permission to read '$wfmux_config'"
					. $wfmux_config        || die "could not source configuration file"
				fi
				;;
			*)
				die "'$1' is an unrecognized option, please try \`$program --help'"
				;;
		esac
		shift
	done
	[ $gave_config = true ] && check_config_variables
	eval "$operation"
}

## Check if variables are unset or null	and if set then
## check if the data is somehow our expectation.
## we won't have to rely on `set -u`, we would want to output a custom 
## error message if one of these variables aren't set/sane.
check_config_variables() {
	_error="$program: ('$config_file'):"

	for parameter in use_xdg searcher explorer window_attributes_rest tbind_ops dash_color \
	                 window_attributes_file_selector project_directory tbind_select tbind_explore \
					 window_attributes_input_box runner; do
		eval "parameter=\${$parameter:-UNSET}"
		[ "$parameter" = UNSET ] && die "$_error '$parameter' isn't set"
	done

	## check if we got sane values
	config_die() { die "$_error content of \`$1' is not valid"; }
	window_regex='[[:digit:]]+x[[:digit:]]+\+[[:digit:]]+\+[[:digit:]]+$'
	{
		expr "$window_attributes_rest"          : "$window_regex" || config_die window_attributes_rest
		expr "$window_attributes_file_selector" : "$window_regex" || config_die window_attributes_file_selector
		expr "$window_attributes_input_box"     : "$window_regex" || config_die window_attributes_input_box
		expr "$use_xdg"                         : 'yes|no$'       || config_die use_xdg
		expr "$dash_color"                      : '[0-9]$'        || config_die dash_color
	} >/dev/null

	for cv in explorer runner searcher; do
		command -v `eval "printf '%s'" "\$$cv"` || die "$error_ '$cv' not found"
	done

	OLD_IFS=$IFS; IFS=$'\n'
	for cv in $project_directory; do
		[ -d "$cv" ] || die "$_error '$cv' is not a directory"
		[ -r "$cv" ] || die "$_error cannot list content of '$cv'"
	done
	IFS=$OLD_IFS
}

display_dashboard() {
	term_h=
	term_w=
	no_color="\033[0m"
	put_color="\033[3${dash_color}m"
	max="awk 'BEGIN{len = 0}; {nlen = length(\$0); if (nlen > len) len = nlen;}; END{print len}'"

	# generate help message for the dashboard
	gen_key_helper() {
		cat <<-EOF
			The following are tmux bindings related to WFMUX.

			M-$tbind_select: fuzzyly open project files
			M-$tbind_explorer: open file manager
			M-$tbind_ops: fuzzyly select other wfmux operations

			input any key to exit dashboard
		EOF
	}
	_print() { printf "\033[$1;$2f$3" >/dev/tty; }

	# save initial terminal setting and will set it back after exiting dashboard
	init_stty=$(stty -g)
	stty -cooked -echo time 0 min 1
	printf "${alt_screen}${hide_cur}${clear_screen}${put_color}"

	(
		while true; do
			[ "$(stty -F /dev/tty size)" = "$term_h $term_w" ] && { sleep 2; continue; }

			term_h=$(stty -F /dev/tty size | cut -d' ' -f1)
			term_w=$(stty -F /dev/tty size | cut -d' ' -f2)
			if   [ $term_h -lt 32 -o $term_w -lt 97  ]; then _size=ss
			elif [ $term_h -lt 43 -o $term_w -lt 155 ]; then _size=ms
			else                                             _size=ls
			fi

			eval 'logo_h=$(printf "%s" "$logo_'$_size'" | wc -l);
				  logo_w=$(printf "%s" "$logo_'$_size'" | eval "$max")'

			logo_h=$(expr $logo_h + `gen_key_helper | wc -l`)
			gen_w=$(gen_key_helper | eval "$max")

			x=$(expr $term_w / 2 - $logo_w / 2)
			y=$(expr $term_h / 2 - $logo_h / 2)

			[ $gen_w -gt $logo_w ]                         &&
			gen_x=$(expr $x - \( $gen_w  - $logo_w \) / 2) ||
			gen_x=$(expr $x + \( $logo_w - $gen_w  \) / 2)

			printf "$clear_screen"
			eval 'printf "%s" "$logo_'$_size'"' | {
				while read line; do _print $y $x "$line"; y=$(($y+1)); done
				gen_key_helper | while read line; do _print $y $gen_x "$line"; y=$(($y+1)); done
			}
		done
	) &

	# get key from standard input
	dd if=/dev/tty count=1 bs=1 >/dev/null 2>&1
	kill -SIGKILL $! || : "could exit due to set -e"
	stty "$init_stty"
	printf "${no_color}${show_cur}"
	tput clear
}

## select a project and open a tmux session
## refer to usage() function for more information
open() {
	if tmux list-sessions >/dev/null 2>&1; then
		printf 'Choose an existing session to attach\n\n'
		tmux list-sessions | awk '{print "["NR"] "$0}'
	fi
	printf '%s\n' "$wfmux"
	read -p '⟩⟩ ' input
	tput clear

	if [ -n "$(expr "$input" : '\([0-9][0-9]*\)$')" ]
	then
		session_name=$(tmux list-sessions -F '#S' | sed -n "${input}p")
		[ -n "$session_name" ] && tmux attach-session -t "$session_name"
	else
		if [ -n "$(expr "$input" : '\(F\|f\)$')" ]
		then
			if [ `printf '%s' "$project_directory" | wc -l` -ne 1 ]
			then
				project_directory=$( printf '%s' "$project_directory" | eval "$searcher" )
			fi
			[ -n "$project_directory" ] || return
			[ -r "$project_directory" ] || return

			project_list=$(
			                IFS=$'\n'; 
			                find $project_directory \
                               -mindepth 2          \
							   -type d              \
							   -iname '.git'        \
							   -exec  expr '{}' : '\(.*\)/.git$' \;
			              )
			project_name=$(
			                printf '%s' "$project_list" | 
							sed -nE 's,^.*/(.*)$,\1,p'  |
							awk '{ print "["NR"]:"$0 }' |
			                eval "$searcher"            |
			                tr _ '\034'                 |
			                tr . _
			              )
			[ -z "$project_name" ] && return

			session_name="wfmux-${project_name##\[*\]:}"
			{
				if ! tmux has-session -t "$session_name"; then
					#(
						# setup runners
					#) &
					display_dashboard
					tmux new-session -s "$session_name"
					# start the watchers
				else
					tmux attach-session -t "$session_name"
				fi
			} 2>/dev/null
		elif [ -z "$input" ]; then return
		else
			tmux new-session -s "$(printf '%s' "$input" | tr _ '\034' | tr . _)"
		fi
	fi
}

## select your project files to open
select()   { :; }
explorer() { :; }
switch()   { :; }
commit()   { :; }
runner()   { :; }


main "$@"
