#!/bin/sh

# Initialize wfmux in your project

ignore=''
generate_files_to_ignore () {
   # Node js project
   if test -f 'package.json' || test -f 'tsconfig.json' ; then
      ignore="${ignore}
node_modules
dist
"
   fi
}

generate_files_to_ignore
if [ -n "$ignore" ]; then
   mkdir -p .wfmux
   printf '%s\n' "$ignore" >>.wfmux/ignore
fi
