#!/bin/sh

PM="${0##*/}"

if [ $# -ne 2 ]
then
	printf "usage: $PM <watcher_name> <watch_config>" >&2
	exit 1
fi

runner="$1"
watcher_name="$2"
watch_config="$3"

{
	which "$runner" >/dev/null 2>&1
	[ $? -eq 0             ] && printf "%s: command '%s' not found\n"     "$PM" "$runner"       && exit 1
	[ ! -f "$watch_config" ] && printf "%s: %s: isn't a valid file\n"     "$PM" "$watch_config" && exit 1
	[ ! -e "$watch_config" ] && printf "%s: %s: does not exist\n"         "$PM" "$watch_config" && exit 1
	[ ! -r "$watch_config" ] && printf "%s: %s: has no read permission\n" "$PM" "$watch_config" && exit 1

	cmd=`cat "$watch_config" | sed -nE "s/^s:[$watcher_name]: (.*):(e|d)$/\1/p"`
	[ -z "$cmd" ] && printf "%s: unknown watcher '%s'" "$PM" "$cmd" && exit 1
} >&2

dump_paths() {
	cat "$watch_config" | sed -E "/^s:[$watcher_name]:e/,/^e:[$watcher_name]:e/p" | tail -n +2 | sed '$d'
}

case "$runner" in
	entr) dump_paths | entr -nr $cmd ;;
	*) : ;;
esac
